### ISSUE TITLE
link directly to linear algebra quickref

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/fcla#89]
"(Look for a linear algebra “Quick Reference” sheet at the Sage website.)"

But probably it should be directly linked, because it's not obvious to a newbie scanner where to look - and in fact I think they might be on the wiki?  I'm not sure of the right solution here (especially if URLs change), but anyway probably a slightly better link could be found than the main website, since that link was already provided in the previous sentence.

**Comment by rbeezer** [comment]
I've added the link to the wiki area, which seems pretty stable.

Natural Google Search is the first hit anyway.  ;-)

At a2220ed5d2adba9efd35451789c881dffa27a84e
