### ISSUE TITLE
misleading archetype statement

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/fcla#91]
"Each archetype (Archetypes) that is a system of equations begins by listing some specific solutions."

No, it doesn't, not until you click to the full analysis, and of course nothing in the print link.

**Comment by rbeezer** [comment]
I think solutions are easily visible in the newer version at:

http://linear.pugetsound.edu/fcla/appendix-A.html

Archetypes predate PreTeXt, and so still need some attention to become whole.  We'll get there.  Thanks.
