### ISSUE TITLE
clarify augmented line bar

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/fcla#92]
"This matrix will be written as [ A | b]"

But usually they aren't.  I find this happens with other LA texts as well.  Should be clarified that you will not have a big honking line in every augmented matrix.  (Or, better, that you WILL have such a line!  I find it to be much clearer in the classroom and text as to which matrices, exactly, are augmented.)

**Comment by rbeezer** [comment]
Right!  Symbolic v. concrete.  I'm adding a bit of clarification.  And **sometime** should act on new #99.  Thanks.

**Comment by rbeezer** [comment]
AT cc780c254c81fc89022ff5aeabde8abe78db3174
