### ISSUE TITLE
bad rendering - possible extra comma?

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/fcla#95]
In ./knowls/proof.SMEZV.knowl, we see something weird (see the actual page at http://linear.ups.edu/html/section-VS.html) which I think might come from the comma here?

    <![CDATA[&&\alpha\neq 0]]>, <acroref type="property" acro="MICN" />\\

**Comment by kcrisman** [comment]
(It's also in the pdf.)

**Comment by rbeezer** [comment]
I think this is all fixed up in newer versions.

http://linear.pugetsound.edu/fcla/section-VS.html#theorem-SMEZV

That HTML link is the old "green" version, which needs to be retired.  (Yes, its a mess.  Seems other projects have diverted my attention for too long...)

Thanks.  More shortly.

**Comment by kcrisman** [comment]
>
>
> I think this is all fixed up in newer versions.
>
Okay, I'll trust you on that!

**Comment by rbeezer** [comment]
PDF is good too.
