### ISSUE TITLE
a_m = 1

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/fcla#96]
In src/section-EE.xml we have 
```
<p>Define the polynomial
<equation>
p(x)=a_0+a_1x+a_2x^2+a_3x^3+\cdots+a_mx^m
</equation>
</p>
```
But really it should be `+\cdots+a_{m-1}x^{m-1}+x^m`, by the comments in the previous paragraph, and by the fact that it factors into linear terms with coefficient 1 in the next paragraph `(x-b_m)`.

**Comment by rbeezer** [comment]
Good catch!  I am writing new material that will rely even more on this result, so your report is very timely.  Yes, timely.  ;-)

**Comment by kcrisman** [comment]
> Good catch! I am writing new material that will rely even more on this
> result, so your report is very timely. Yes, timely. ;-)
>
>
Given how many people have helped catch things like this in my book, I
recognize it's *always* timely!

**Comment by rbeezer** [comment]
;-)

At 3badd05fe717039f9cc89198eaad9de6ca1d87da
