### ISSUE TITLE
Form should have six digits (abcdef)

### ISSUE THREAD

**Issue by dl2n** [rbeezer/fcla#98]
https://github.com/rbeezer/fcla/blob/55896fd7cbfd7d963dde6a249d77f48a590e0de1/src2/section-SSLE.xml#L574

The solution to C51 is a the six digit number being represented as abcdef - the final "f" is missing, e.g. should read as abcdef = 563910. not abcde = 563910

**Comment by rbeezer** [comment]
Good catch, Dan.  Thank-you.

Fix, with credit, at 289c4c770541cba10967c4988c70c3eb8839e234
